# Generated by Django 4.1 on 2022-10-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='intrest_rate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
