# Generated by Django 3.0 on 2022-08-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0002_auto_20220731_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_created',
        ),
    ]
