# Generated by Django 4.1 on 2022-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0002_loan_intrest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_of_repayemnt',
            field=models.DateTimeField(null=True),
        ),
    ]
