# Generated by Django 3.0 on 2022-10-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0002_auto_20221019_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='collateral1_attachements',
            field=models.ImageField(upload_to='uploads/Collatreals/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collateral2_attachements',
            field=models.ImageField(upload_to='uploads/Collatreals/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id_att',
            field=models.ImageField(upload_to='uploads/memberIDs/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_photo',
            field=models.ImageField(upload_to='uploads/memberPhotos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_keen_id',
            field=models.ImageField(upload_to='uploads/nextofKeenIDs/'),
        ),
    ]
