# Generated by Django 4.1 on 2022-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0003_alter_loan_date_of_repayemnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_of_repayemnt',
            field=models.DateField(null=True),
        ),
    ]
