# Generated by Django 4.1 on 2022-10-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0004_alter_loan_date_of_repayemnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepayLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('date_of_loan_repayment', models.DateTimeField(auto_now=True, null=True)),
                ('repay_in', models.CharField(max_length=200, null=True)),
                ('paid_by', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
    ]
