# Generated by Django 3.1.1 on 2022-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0004_auto_20220802_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_type',
            field=models.CharField(choices=[('NATIONAL ID', 'NATIONAL ID'), ('PASSPORT', 'PASSPORT'), ('DRIVING PERMIT', 'DRIVING PERMIT')], max_length=200, null=True),
        ),
    ]
