# Generated by Django 4.1 on 2022-10-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0005_auto_20220802_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saccoadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(max_length=200, null=True)),
                ('date_of_transaction', models.DateTimeField(auto_now=True, null=True)),
                ('withdrawn_by', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING')], max_length=200)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
        migrations.CreateModel(
            name='Desposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(max_length=200, null=True)),
                ('date_of_transaction', models.DateTimeField(auto_now=True, null=True)),
                ('deposited_by', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING')], max_length=200)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teleka.member')),
            ],
        ),
    ]
