# Generated by Django 4.1 on 2022-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0007_rename_desposit_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
