# Generated by Django 4.1 on 2022-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleka', '0008_alter_deposit_amount_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=200),
        ),
    ]
